
export const EN_WORDS = {
    PROFILE : "Profile", 
    DEVOLOPER : "Devoloper",
    SITE : "Go Site",
    CONTENT : "CONTENT",
    PUBLISHER : "Publisher",
    GENRE : "Genre",
    ADD_DEVOLOPER : 'Add Devoloper',
    LIST_DEVOLOPER : 'List Devoloper', 
    ADD_PUBLISHER : 'Add Publisher',
    LIST_PUBLISHER : "List PUBLISHER",
    ADD_GENRE : 'Add Genre',
    LIST_GENRE : 'List Genre',
    PLATFORM : 'Platform',
    ADD_PLATFORM : 'Add Platform',
    LIST_PLATFORM : 'List Platform',
    NEWS : 'News',
    STREAM : 'Streaming',
    GAMES_REVIEWS : 'Game Reviews',
    HELP : 'Help',
    CHEATS : 'Cheats',
    CATEGORY : 'Category',
    ADD_CATEGORY : 'Add Category',
    LIST_CATEGORY : 'List Category',
}