import {WORDS_Tem} from './WORDS'
export const EN_WORDS : WORDS_Tem= {
    PROFILE : "Profile", 
    DEVOLOPER : "Developer",
    SITE : "Go Site",
    CONTENT : "CONTENT",
    PUBLISHER : "Publisher",
    GENRE : "Genre",
    ADD_DEVOLOPER : 'Add Developer',
    LIST_DEVOLOPER : 'List Developer', 
    ADD_PUBLISHER : 'Add Publisher',
    LIST_PUBLISHER : "List PUBLISHER",
    ADD_GENRE : 'Add Genre',
    LIST_GENRE : 'List Genre',
    PLATFORM : 'Platform',
    ADD_PLATFORM : 'Add Platform',
    LIST_PLATFORM : 'List Platform',
    NEWS : 'News',
    STREAM : 'Streaming',
    GAMES_REVIEWS : 'Game Reviews',
    HELP : 'Help',
    CHEATS : 'Cheats',
    CATEGORY : 'Category',
    ADD_CATEGORY : 'Add Category',
    LIST_CATEGORY : 'List Category',
    SAVE_ARTICLE : 'Save Article',
    TITLE_ARTICLE : 'Title Article',
    SELECT_CATEGORY : "Select Category",
    TITLE_SEO_ARTICLE : 'Title Article SEO',
    DES_SEO_ARTICLE : 'Describe Article SEO',
    TITLE_GAME : 'Title Game',
    CHOOSE_GENRES : 'Choose Genre(s)',
    CHOOSE_DEVELOPER : 'Choose Developer',
    CHOOSE_PUBLISHER : 'Choose Publisher',
    CHOOSE_PLATFORMS : 'Choose Platform(s)',
    URL_PUBLISHER : 'Url Publisher',
    OS : 'Operating system',
    MIN_CPU : 'Minimum Processor Requirements',
    MAX_CPU : 'Maximum Processor Requirements',
    MIN_RAM : "Minimum RAM",
    MAX_RAM : "Recommended RAM",
    DRIVERS : "Drivers",
    NETWORK : "Network",
    SPACE_DISK : 'Disk Space',
    ADD_HELMET_GAMEPOST : 'Add a gaming article',
    CREATE_CATEGORY  : 'Create category',
    SAVE_CATEGORY : 'Save Category',
    WRITE_NAME_CATEGORY : 'Write Name Category',
    CREATE_DEVELOPER : 'Create Developer',
    SAVE_DEVELOPER : 'Save Developer',
    WRITE_NAME_DEVELOPER : 'Write Name Developer',
    CREATE_GENRE : "Create Genre",
    SAVE_GENRE : "Save Genre",
    WRITE_NAME_GENRE : 'Write Name Genre',
    CREATE_PUBLISHER : 'Create Publisher',
    SAVE_PUBLISHER : 'Save Publisher',
    WRITE_PUBLISHER : 'Write Name Publisher',
    TITLE_SEO : 'GameForYou: Latest Game Reviews & News',
    DESCRIPTION_SEO : 'Discover the latest in ga    ming with GameForYou: in-depth reviews, news, and insights on the hottest games and industry trends',
    YOU_FIND_US : 'You can find us:',
    MORE : 'More..',
    US_INTERESTING : 'You might be interested in',
    LATEST_BLOGS : 'Latest Blogs',
    LatestGamingNews : 'Latest gaming news',
}