import {WORDS_Tem} from './WORDS'
export const PL_WORDS : WORDS_Tem = {
    PROFILE : "Profil", 
    DEVOLOPER : "Deweloper",
    SITE : "Przejdź do witryny",
    CONTENT : "TREŚĆ",
    PUBLISHER : "Wydawca",
    GENRE : "Gatunek muzyczny",
    ADD_DEVOLOPER : 'Dodaj programistę',
    LIST_DEVOLOPER : 'Lista deweloperów', 
    ADD_PUBLISHER : 'Dodaj wydawcę',
    LIST_PUBLISHER : "Wydawca listy",
    ADD_GENRE : 'Dodaj gatunek',
    LIST_GENRE : 'Lista gatunków',
    PLATFORM : 'Platforma',
    ADD_PLATFORM : 'Dodaj platformę',
    LIST_PLATFORM : 'Platforma Lista',
    NEWS : 'Aktualności',
    STREAM : 'Strumień',
    GAMES_REVIEWS : 'Recenzje gier',
    HELP : 'Help',
    CHEATS : 'Cheats',
    CATEGORY : 'Kategoria',
    ADD_CATEGORY : 'Dodaj kategorię',
    LIST_CATEGORY : 'Kategoria listy',
    SAVE_ARTICLE : 'Zapisz artykuł',
    TITLE_ARTICLE : 'Tytuł artykułu',
    SELECT_CATEGORY : 'Wybierz kategorię',
    TITLE_SEO_ARTICLE : ' SEO',
    DES_SEO_ARTICLE : 'Opis artykułu SEO',
    TITLE_GAME : 'Nazwa gry',
    CHOOSE_GENRES : 'Wybierz gatunek',
    CHOOSE_DEVELOPER : 'Wybierz programistę',
    CHOOSE_PUBLISHER : 'Wybierz Wydawca',
    CHOOSE_PLATFORMS : 'Wybierz platformy',
    URL_PUBLISHER : 'Strona wydawcy',
    OS : 'System operacyjny',
    MIN_CPU : 'Minimalne wymagania dotyczące procesora',
    MAX_CPU : 'Maksymalne wymagania dotyczące procesora',
    MIN_RAM : "Minimalna ilość pamięci RAM",
    MAX_RAM : "Zalecana pamięć RAM",
    DRIVERS : "Kierowcy",
    NETWORK : "Internet",
    SPACE_DISK : 'Miejsca na dysku',
    ADD_HELMET_GAMEPOST : 'Dodaj artykuł o grach',
}