import {WORDS_Tem} from './WORDS'
export const PL_WORDS : WORDS_Tem = {
    PROFILE : "Profil", 
    DEVOLOPER : "Deweloper",
    SITE : "Przejdź do witryny",
    CONTENT : "TREŚĆ",
    PUBLISHER : "Wydawca",
    GENRE : "Gatunek muzyczny",
    ADD_DEVOLOPER : 'Dodaj programistę',
    LIST_DEVOLOPER : 'Lista deweloperów', 
    ADD_PUBLISHER : 'Dodaj wydawcę',
    LIST_PUBLISHER : "Wydawca listy",
    ADD_GENRE : 'Dodaj gatunek',
    LIST_GENRE : 'Lista gatunków',
    PLATFORM : 'Platforma',
    ADD_PLATFORM : 'Dodaj platformę',
    LIST_PLATFORM : 'Platforma Lista',
    NEWS : 'Aktualności',
    STREAM : 'Strumień',
    GAMES_REVIEWS : 'Recenzje gier',
    HELP : 'Help',
    CHEATS : 'Cheats',
    CATEGORY : 'Kategoria',
    ADD_CATEGORY : 'Dodaj kategorię',
    LIST_CATEGORY : 'Kategoria listy',
    SAVE_ARTICLE : 'Zapisz artykuł',
    TITLE_ARTICLE : 'Tytuł artykułu',
    SELECT_CATEGORY : 'Wybierz kategorię',
    TITLE_SEO_ARTICLE : ' SEO',
    DES_SEO_ARTICLE : 'Opis artykułu SEO',
    TITLE_GAME : 'Nazwa gry',
    CHOOSE_GENRES : 'Wybierz gatunek',
    CHOOSE_DEVELOPER : 'Wybierz programistę',
    CHOOSE_PUBLISHER : 'Wybierz Wydawca',
    CHOOSE_PLATFORMS : 'Wybierz platformy',
    URL_PUBLISHER : 'Strona wydawcy',
    OS : 'System operacyjny',
    MIN_CPU : 'Minimalne wymagania dotyczące procesora',
    MAX_CPU : 'Maksymalne wymagania dotyczące procesora',
    MIN_RAM : "Minimalna ilość pamięci RAM",
    MAX_RAM : "Zalecana pamięć RAM",
    DRIVERS : "Kierowcy",
    NETWORK : "Internet",
    SPACE_DISK : 'Miejsca na dysku',
    ADD_HELMET_GAMEPOST : 'Dodaj artykuł o grach',
    CREATE_CATEGORY  : 'Utwórz kategorię',
    SAVE_CATEGORY : 'Zapisz kategorię',
    WRITE_NAME_CATEGORY : 'Wpisz nazwę kategorii',
    CREATE_DEVELOPER : 'Utwórz programistę',
    SAVE_DEVELOPER : 'Zapisz programistę',
    WRITE_NAME_DEVELOPER : 'Wpisz nazwę programisty',
    CREATE_GENRE : "Utwórz gatunek",
    SAVE_GENRE : "Zapisz gatunek",
    WRITE_NAME_GENRE : 'Wpisz nazwę gatunku',
    CREATE_PUBLISHER : 'Utwórz wydawcę',
    SAVE_PUBLISHER : 'Zapisz wydawcę',
    WRITE_PUBLISHER : 'Wpisz nazwę wydawcy',
    TITLE_SEO : 'GameForYou: Najnowsze Recenzje i Wiadomości',
    DESCRIPTION_SEO : 'Odkryj najnowsze gry z GameForYou: szczegółowe recenzje, wiadomości i przeglądy najgorętszych gier i trendów branżowych.',
    YOU_FIND_US : 'Możesz nas znaleźć',
    MORE : 'Więcej..',
    US_INTERESTING : 'Może Cię zainteresuje',
    LATEST_BLOGS : 'Najnowsze blogi',
    LatestGamingNews : 'Najnowsze wiadomości ze świata gier',
    DETAILS : 'Więcej szczegółów',
    DATA_RELASE : 'Data wydania',
    SITE_GAME : 'Strona internetowa gry',
    USER_RATING : 'Ocena użytkownika',
    WRITE_A_REVIEW : 'Napisać recenzję',
    MY_RATING : 'Mój ranking',
    TITLE_OPTIONAL : 'Tytuł (opcjonalnie)',
    DES_OPTIONAL : 'Opis (opcjonalnie)',
    POSITIVE_TITLE : 'Zalety',
    NEGATIVE_TITLE : 'Wady',
    SEND_COMMENT : 'Prześlij komentarz',
    CHOOSE_CATEGORY : 'Wybierz kategorię',
    CHOOSE_TAG : 'Wybierz Etykietę',
    CREATE_TAG : 'Utwórz tag',
    WRITE_NAME_TAG : 'Napisz tag',
    SAVE_TAG : 'Zapisz znacznik',
    DES_LIST_ARTICLE_SEO : 'Aktualności ze świata gier: Bądź na bieżąco z najnowszymi wydarzeniami, recenzjami i ogłoszeniami ze świata gier. Odkrywaj najgorętsze trendy w branży gamingowej na jednej platformie.',
    TITLE_LIST_ARTICLE_SEO : 'Aktualności ze świata gier: Gorące trendy, recenzje i ogłoszenia w świecie gier',
    BREADCRUMBS_HOME : 'Dom',
    BREADCRUMBS_LIST_ARTICLE: 'Wiadomości z gry',
    SET_TAG_FOR_ARTICLE : 'Tagi',
    ADD_ARTICLE : 'Dodaj artykuł',
    TITLE_GAME_URL_SEO : 'url',
    HOME : 'Dom',
    COMMENTS : 'Uwagi',
    BLOGS : 'Blogi',
    ARTICLEBYGAME : 'Najnowsze wiadomości, aktualizacje i ekscytujące wydarzenia dla prawdziwych fanów',
    DES_ARTICLEBYGAME : 'Dowiedz się o wszystkich najnowszych wydarzeniach i aktualizacjach w świecie. Ważne wiadomości, ekscytujące aktualizacje i fascynujące wydarzenia czekają na ciebie!',
    TITLE_COMMENTS_BY_GAME : 'Zbiór recenzji - Zapoznaj się z opiniami graczy i ekspertów, aby pełniej doświadczyć gry',
    DES_COMMENTS_BY_GAME : 'Najlepsze recenzje od graczy i ekspertów, aby w pełni zanurzyć się w świat gry.',
}