import {WORDS_Tem} from './WORDS'
export const RU_WORDS : WORDS_Tem = {
    PROFILE : "Профиль",
    DEVOLOPER : "Разработчик",
    SITE : "Перейти на сайт",
    CONTENT : "Контент",
    PUBLISHER : "Издатель",
    GENRE : "Жанр",
    ADD_DEVOLOPER : 'Добавить Разработчика',
    LIST_DEVOLOPER : 'Список Разработчиков', 
    ADD_PUBLISHER : 'Добавить издателя',
    LIST_PUBLISHER : "Список Издателей",
    ADD_GENRE : 'Добавить Жанр',
    LIST_GENRE : 'Список Жанров',
    PLATFORM : 'Платформа',
    ADD_PLATFORM : 'Добавить Платформу',
    LIST_PLATFORM : 'Список Платформ',
    NEWS : 'Новости',
    STREAM : 'Стримы',
    GAMES_REVIEWS : 'Обзоры игр',
    HELP : 'Помощь',
    CHEATS : 'Cheats',
    CATEGORY : 'Категория',
    ADD_CATEGORY : 'Добавить Категорию',
    LIST_CATEGORY : 'Список Категорий',
    SAVE_ARTICLE : 'Сохранить статью',
    TITLE_ARTICLE : 'Назвние статьи',
    SELECT_CATEGORY : 'Выбрать Категорию',
    TITLE_SEO_ARTICLE : 'Название статьи SEO',
    DES_SEO_ARTICLE : 'Описание статьи SEO',
    TITLE_GAME : 'Название игры',
    CHOOSE_GENRES : 'Выбрать Жанр(ы)',
    CHOOSE_DEVELOPER : 'Выбрать разработчика',
    CHOOSE_PUBLISHER : 'Выбрать Издателя',
    CHOOSE_PLATFORMS : 'Выбрать Платформу(ы)',
    URL_PUBLISHER : 'Сайт Издателя',
    OS : 'Операционная Система',
    MIN_CPU : 'Минимальные Требования для процессора',
    MAX_CPU : 'Максимальные Требования для процессора',
    MIN_RAM : "Минимальная  Оперативная Память",
    MAX_RAM : "Рекомендованные Оперативная Память",
    DRIVERS : "Драйвера",
    NETWORK : "Сеть",
    SPACE_DISK : 'Место на диске',
    ADD_HELMET_GAMEPOST : 'Добавить  игровою статью',
    CREATE_CATEGORY  : 'Создать Категорию',
    SAVE_CATEGORY : 'Создать Категорию',
    WRITE_NAME_CATEGORY : 'Написать название Категории',
    CREATE_DEVELOPER : 'Создать Разработчика',
    SAVE_DEVELOPER : 'Сохранить Разработчика',
    WRITE_NAME_DEVELOPER : 'Напишите название разработчика',
    CREATE_GENRE : "Создать Категорию",
    SAVE_GENRE : "Сохранить Категорию",
    WRITE_NAME_GENRE : 'Написать Название Жанра',
    CREATE_PUBLISHER : 'Создать Издателя',
    SAVE_PUBLISHER : 'Сохранить Издателя',
    WRITE_PUBLISHER : 'Написать Название Издателя',
    TITLE_SEO : 'GameForYou: Последние Обзоры Игр и Новости',
    DESCRIPTION_SEO : 'Погрузитесь в мир игр с GameForYou: подробные обзоры, новости и аналитика по самым актуальным играм и трендам индустрии.',
    YOU_FIND_US : 'Ты можешь нас найти:',
    MORE : 'Больше..',
    US_INTERESTING : 'Вас заинтересует',
    LATEST_BLOGS : 'Свежие блоги',
    LatestGamingNews : 'Последние игровые новости',
    DETAILS : 'Подробней',
    DATA_RELASE : 'Дата Выхода',
    SITE_GAME : 'Сайт игры',
    USER_RATING : 'Оценка пользователей',
    WRITE_A_REVIEW : 'Написать отзыв',
    MY_RATING : 'Мой рейтинг',
    TITLE_OPTIONAL : 'Заголовок (по желанию)',
    DES_OPTIONAL : 'Описание (по желанию)',
    POSITIVE_TITLE : 'Преимущества',
    NEGATIVE_TITLE : 'Недостатки',
    SEND_COMMENT : 'Отправить комментарий',
} 