export const RU_WORDS = {
    PROFILE : "Профиль",
    DEVOLOPER : "Разработчик",
    SITE : "Перейти на сайт",
    CONTENT : "Контент",
    PUBLISHER : "Издатель",
    GENRE : "Жанр",
    ADD_DEVOLOPER : 'Добавить Разработчика',
    LIST_DEVOLOPER : 'Список Разработчиков', 
    ADD_PUBLISHER : 'Добавить издателя',
    LIST_PUBLISHER : "Список Издателей",
    ADD_GENRE : 'Добавить Жанр',
    LIST_GENRE : 'Список Жанров',
    ADD_PLATFORM : 'Добавить Платформу',
    LIST_PLATFORM : 'Список Платформ',
    NEWS : 'Новости',
    STREAM : 'Стримы',
    GAMES_REVIEWS : 'Обзоры игр',
    HELP : 'Помощь',
    CHEATS : 'Cheats',
    CATEGORY : 'Категория',
    ADD_CATEGORY : 'Добавить Категорию',
    LIST_CATEGORY : 'Список Категорий',
} 