import { WORDS_Tem } from "./WORDS";
export const UA_WORDS: WORDS_Tem = {
  PROFILE: "Профіль",
  DEVOLOPER: "Розробник",
  SITE: "Перейти на сайт",
  CONTENT: "Контент",
  PUBLISHER: "Видавець",
  GENRE: "Жанр",
  ADD_DEVOLOPER: "Додати Розробника",
  LIST_DEVOLOPER: "Список Розробників",
  ADD_PUBLISHER: "Додати видавця",
  LIST_PUBLISHER: "Список Видавців",
  ADD_GENRE: "Додати Жанр",
  LIST_GENRE: "Список Жанрів",
  PLATFORM: "Платформа",
  ADD_PLATFORM: "Додати Платформу",
  LIST_PLATFORM: "Список Платформ",
  NEWS: "Новини",
  STREAM: "Стріми",
  GAMES_REVIEWS: "Огляди на ігри",
  HELP: "Допомога",
  CHEATS: "Cheats",
  CATEGORY: "Категорія",
  ADD_CATEGORY: "Додати Катогорію",
  LIST_CATEGORY: "Список Категорію",
  SAVE_ARTICLE: "Зберегти статью",
  TITLE_ARTICLE: "Назва статьї",
  SELECT_CATEGORY: "Обрати Категоію",
  TITLE_SEO_ARTICLE: "Назва статьї SEO",
  DES_SEO_ARTICLE: "Опис статьї SEO",
  TITLE_GAME: "Назва Ігри",
  CHOOSE_GENRES: "Обрати Жанр(и)",
  CHOOSE_DEVELOPER: "Обрати Розробника",
  CHOOSE_PUBLISHER: "Обрати Видавця",
  CHOOSE_PLATFORMS: "Обрати Платформу(и)",
  URL_PUBLISHER: "Сайт Видавця",
  OS: "Операційна Система",
  MIN_CPU: "Мінімальні вимоги для процесора",
  MAX_CPU: "Максимальні вимоги для процесора",
  MIN_RAM: "Мінімальна Оперативна Пам'ять",
  MAX_RAM: "Рекомендована Оперативна Пам'ять",
  DRIVERS: "Драйвера",
  NETWORK: "Мережа",
  SPACE_DISK: "Місце на Диску",
  ADD_HELMET_GAMEPOST: "Додати статью на ігрову тему",
  CREATE_CATEGORY: "Створити Категорію",
  SAVE_CATEGORY: "Зберегти Категорію",
  WRITE_NAME_CATEGORY: "Написати Назву Категорії",
  CREATE_DEVELOPER: "Створити Розробника",
  SAVE_DEVELOPER: "Зберегти Розробника",
  WRITE_NAME_DEVELOPER: "Напишіть назву розробника",
  CREATE_GENRE: "Створити Категорію",
  SAVE_GENRE: "Зберегти Категорію",
  WRITE_NAME_GENRE: "Написати назву розробника",
  CREATE_PUBLISHER: "Створити Видавця",
  SAVE_PUBLISHER: "Зберегти Видавця",
  WRITE_PUBLISHER: "Написати Назву Видаця",
  TITLE_SEO: "GameForYou: Нові Огляди Ігор, Гарячі Новини",
  DESCRIPTION_SEO:
    "Дізнайтеся про новинки в світі ігор з GameForYou: детальні огляди, новини та огляди гарячих ігор та трендів індустрії.",
  YOU_FIND_US: "Ви можете знайти нас тут:",
  MORE: "Більше..",
  US_INTERESTING: "Вас зацікавить",
  LATEST_BLOGS: "Свіжі блоги",
  LatestGamingNews: "Останні ігрові новини",
  DETAILS: "Детальніше",
  DATA_RELASE: "Дата виходу",
  SITE_GAME: "Сайт ігри",
  USER_RATING: "Оцінка користувачів",
  WRITE_A_REVIEW: "Написати відгук",
  MY_RATING: "Мій рейтинг",
  TITLE_OPTIONAL: "Заголовок (за бажанням)",
  DES_OPTIONAL: "Опис (за бажанням)",
  POSITIVE_TITLE: "Переваги",
  NEGATIVE_TITLE: "Недоліки",
  SEND_COMMENT: "Надіслати коментар",
  CHOOSE_CATEGORY: "Обрати Категорію",
  CHOOSE_TAG: "Обрати Мітку",
  CREATE_TAG: "Створити Мітку",
  WRITE_NAME_TAG: "Написати назву мітки",
  SAVE_TAG: "Зберегти мітку",
  DES_LIST_ARTICLE_SEO:
    "Ігрові новини: дізнавайтеся першими про актуальні події, огляди та анонси в світі ігор. Усі гарячі тренди геймінгу на одному ресурсі",
  TITLE_LIST_ARTICLE_SEO:
    "Ігрові новини: гарячі тренди, огляди та анонси у світі ігор",
  BREADCRUMBS_HOME: "Головна",
  BREADCRUMBS_LIST_ARTICLE: "Ігрові Новини",
  SET_TAG_FOR_ARTICLE: "Теги",
  ADD_ARTICLE: "Додати Статью",
  TITLE_GAME_URL_SEO: "url",
  HOME: "Головна",
  COMMENTS: "Коментарі",
  BLOGS: "Блог",
  ARTICLEBYGAME:
    "Гарячі новини, оновлення та цікаві події для справжніх шанувальників",
  DES_ARTICLEBYGAME:
    "Дізнайтеся всі останні події та оновлення в світі. Важливі новини, захоплюючі оновлення та захоплюючі події чекають на вас!",
  TITLE_COMMENTS_BY_GAME:
    "Список відгуків від гравців та експертів для повного занурення в світ гри",
  DES_COMMENTS_BY_GAME:
    "Кращі відгуки гравців та експертів для повного занурення в світ гри.",
  GAME_SOURCE: "сайт",
  TODAY: "Сьогодні",
  TOMORROW: "Вчора",
};
