
export const UA_WORDS = {
    PROFILE : "Профіль",
    DEVOLOPER : "Розробник",
    SITE : "Перейти на сайт",
    CONTENT : "Контент",
    PUBLISHER : "Видавець",
    GENRE : "Жанр",
    ADD_DEVOLOPER : 'Додати Розробника',
    LIST_DEVOLOPER : 'Список Розробників', 
    ADD_PUBLISHER : 'Додати видавця',
    LIST_PUBLISHER : "Список Видавців",
    ADD_GENRE : 'Додати Жанр',
    LIST_GENRE : 'Список Жанрів',
    ADD_PLATFORM : 'Додати Платформу',
    LIST_PLATFORM : 'Список Платформ',
    NEWS : 'Новини',
    STREAM : 'Стріми',
    GAMES_REVIEWS : 'Огляди на ігри',
    HELP : 'Допомога',
    CHEATS : 'Cheats',
    CATEGORY : 'Категорія',
    ADD_CATEGORY : 'Додати Катогорію',
    LIST_CATEGORY : 'Список Категорію',
}